on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      dotnet-additional-version:
        required: false
        type: string
      create-github-release:
        required: false
        type: boolean
        default: false
      packages-path:
        required: false
        type: string
        default: artifacts/packages/*.nupkg
      install-sql-server:
        required: false
        type: boolean
        default: false
    secrets:
      NUGET_TOKEN:
        required: true

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      is_release: ${{ steps.analyze_tag.outputs.is_release }}
      is_prerelease: ${{ steps.analyze_tag.outputs.is_prerelease }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Setup additional dotnet
        if: ${{ inputs.dotnet-additional-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-additional-version }}
          
      - name: Run the action
        if: ${{ inputs.install-sql-server }}
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine, sqlpackage, localdb

      - name: Print build info
        shell: pwsh
        run: ./scripts info

      - name: Build
        shell: pwsh
        run: ./scripts build -NoBuildInfo

      - name: Test
        shell: pwsh
        run: ./scripts test -NoBuildInfo

      - name: Pack
        shell: pwsh
        run: ./scripts pack -NoBuildInfo

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts

      - name: Analyze tag ${{ github.ref }}
        id: analyze_tag
        shell: bash
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "Release tag detected"
            echo "::set-output name=is_release::true"
            if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+.*- ]]; then
              echo "Prerelease tag detected"
              echo "::set-output name=is_prerelease::true"
            fi
          fi

  release:
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.outputs.is_release == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts

      - name: Publish packages to nuget
        run: dotnet nuget push ${{ inputs.packages-path }} --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json

      - name: Create GitHub release
        if: ${{ inputs.create-github-release }}
        uses: ncipollo/release-action@v1
        with:
          prerelease: ${{ needs.build.outputs.is_prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
